import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../services/api';
import Alert from '../components/Alert';
import Spinner from '../components/Spinner';

export default function Flashcards() {
  const [cards, setCards] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [index, setIndex] = useState(0);
  const [flipped, setFlipped] = useState(false);
  const [known, setKnown] = useState({});
  const [filter, setFilter] = useState('all');

  useEffect(() => {
    let active = true;
    const load = async () => {
      setLoading(true);
      try {
        const { data } = await api.get('/ai/flashcards');
        if (active) setCards(data.flashcards);
      } catch (err) {
        if (active) setError(err.message);
      } finally {
        if (active) setLoading(false);
      }
    };
    load();
    return () => {
      active = false;
    };
  }, []);

  const visible = useMemo(() => {
    if (filter === 'all') return cards;
    if (filter === 'unknown') return cards.filter((c, i) => !known[c._id ?? i]);
    return cards.filter((c) => c.difficulty === filter);
  }, [cards, filter, known]);

  const current = visible[index];

  const mark = (value) => {
    if (!current) return;
    setKnown((k) => ({ ...k, [current._id]: value }));
    setFlipped(false);
    setIndex((i) => (i + 1) % Math.max(1, visible.length));
  };

  if (loading) return <Spinner label="Loading flashcards..." />;

  return (
    <div className="mx-auto max-w-4xl px-4 py-10 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-slate-900">Flashcards</h1>
      <p className="mt-1 text-sm text-slate-500">
        Active recall practice generated by AI. Click a card to reveal the answer.
      </p>

      <Alert type="error" onClose={() => setError('')}>{error}</Alert>

      {cards.length === 0 ? (
        <div className="card mt-8 px-6 py-16 text-center">
          <p className="font-semibold text-slate-700">No flashcards yet</p>
          <p className="mt-1 text-sm text-slate-500">
            Open a study material and generate flashcards to start practising.
          </p>
          <Link to="/materials" className="btn-primary mt-4">Go to study materials</Link>
        </div>
      ) : (
        <>
          <div className="mt-6 flex flex-wrap gap-2">
            {['all', 'unknown', 'Easy', 'Medium', 'Hard'].map((f) => (
              <button
                key={f}
                onClick={() => {
                  setFilter(f);
                  setIndex(0);
                  setFlipped(false);
                }}
                className={`rounded-full px-4 py-1.5 text-xs font-semibold transition ${
                  filter === f ? 'bg-brand-600 text-white' : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
                }`}
              >
                {f === 'all' ? 'All cards' : f === 'unknown' ? 'Not yet known' : f}
              </button>
            ))}
          </div>

          {visible.length === 0 ? (
            <div className="card mt-6 px-6 py-12 text-center text-sm text-slate-500">
              No cards match this filter.
            </div>
          ) : (
            <>
              <p className="mt-4 text-sm text-slate-500">
                Card {index + 1} of {visible.length}
              </p>

              <div
                onClick={() => setFlipped((v) => !v)}
                className="mt-2 min-h-[260px] cursor-pointer rounded-2xl border border-brand-200 bg-white p-10 text-center shadow-sm transition hover:shadow-md"
              >
                <p className="text-xs font-bold uppercase tracking-wide text-brand-500">
                  {flipped ? 'Answer' : 'Question'}
                </p>
                <p className="mt-4 text-lg font-semibold leading-relaxed text-slate-800">
                  {flipped ? current.answer : current.question}
                </p>
                {flipped && current.materialId?.title && (
                  <p className="mt-4 text-xs text-slate-400">From: {current.materialId.title}</p>
                )}
                <p className="mt-5 text-xs text-slate-400">Click to flip</p>
              </div>

              <div className="mt-5 flex flex-wrap items-center justify-center gap-3">
                <button
                  onClick={() => {
                    setFlipped(false);
                    setIndex((i) => (i - 1 + visible.length) % visible.length);
                  }}
                  className="btn-secondary"
                >
                  Previous
                </button>
                <button onClick={() => mark(false)} className="btn-secondary">
                  Still learning
                </button>
                <button onClick={() => mark(true)} className="btn-primary">
                  I knew this
                </button>
                <button
                  onClick={() => {
                    setFlipped(false);
                    setIndex((i) => (i + 1) % visible.length);
                  }}
                  className="btn-secondary"
                >
                  Next
                </button>
              </div>

              {current.difficulty && (
                <p className="mt-4 text-center">
                  <span
                    className={`badge ${
                      current.difficulty === 'Easy'
                        ? 'bg-emerald-50 text-emerald-700'
                        : current.difficulty === 'Hard'
                        ? 'bg-rose-50 text-rose-700'
                        : 'bg-amber-50 text-amber-700'
                    }`}
                  >
                    {current.difficulty}
                  </span>
                </p>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}
